import asyncio
import os
import sys

# Add the current directory to path so we can import backend
sys.path.insert(0, os.path.abspath('.'))

from app.services.llm_agent import ask_gemini_with_mcp

SESSION_ID = "test_session"

async def test_time():
    print("=" * 50)
    print("TEST 1: Time")
    print("=" * 50)
    response = await ask_gemini_with_mcp("What time is it right now?", SESSION_ID)
    print("Response:", response)
    print()

async def test_weather():
    print("=" * 50)
    print("TEST 2: Weather")
    print("=" * 50)
    response = await ask_gemini_with_mcp("What is the weather in Pune?", SESSION_ID)
    print("Response:", response)
    print()

async def test_location():
    print("=" * 50)
    print("TEST 3: Location")
    print("=" * 50)
    response = await ask_gemini_with_mcp("Where am I located right now?", SESSION_ID)
    print("Response:", response)
    print()

async def test_document():
    print("=" * 50)
    print("TEST 4: Document Generation")
    print("=" * 50)
    response = await ask_gemini_with_mcp(
        "Generate a short PDF document titled 'Test Report' with the content: "
        "'This is a test report generated by the ESP32 AI Desktop Bot. "
        "It validates the document generation pipeline.'",
        SESSION_ID
    )
    print("Response:", response)
    print()

async def main():
    print("\n🚀 ESP32 MCP Tools Test Suite\n")

    await test_time()
    await test_weather()
    await test_location()
    await test_document()

    print("=" * 50)
    print("✅ All tests completed!")
    print("=" * 50)

if __name__ == "__main__":
    asyncio.run(main())
